services:
  - type: web
    name: pollpulse
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        scope: project
      - key: JWT_SECRET
        scope: project
