services:
  - type: web
    name: pollpulse
    runtime: node
    plan: free
    buildCommand: npm install --include=dev --prefix frontend && npm run build --prefix frontend && npm install --production --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://voices-1-kixy.onrender.com
      - key: MONGODB_URI
        scope: project
      - key: JWT_SECRET
        scope: project
